name: matching_pairs
description: "A Flutter game about matching pairs"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^16.1.0
  shared_preferences: ^2.5.3
  http: ^1.5.0
  equatable: ^2.0.7
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
